### ISSUE TITLE
Segmentation fault / Double free

### ISSUE THREAD

**Issue by thierry-f-78** [zhaozg/lua-openssl#141]
Hi,

It seems it have a bug with the memory release and the usage of objects based on lightuserdata. I wrote this code:

```
local c = openssl.cipher.decrypt_new('bf-cbc', "secret_key", "iv")
local out = c:update("msg")
local final = c:final()
c:close()
c = nil
collectgarbage("collect")
```

I obtain a segmentation fault.

```
#0  0x00007ffff740dbe5 in EVP_CIPHER_CTX_cleanup () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff5720a6d in openssl_cipher_ctx_free (L=0x1878f068) at lua-openssl-0.7.1/src/cipher.c:551
#2  0x00000000004d1044 in luaD_precall ()
#3  0x00000000004d1413 in luaD_call ()
#4  0x00000000004d1471 in luaD_callnoyield ()
#5  0x00000000004d089c in luaD_rawrunprotected ()
#6  0x00000000004d16dd in luaD_pcall ()
#7  0x00000000004d288f in GCTM ()
#8  0x00000000004d2932 in runafewfinalizers ()
#9  0x00000000004ce17e in lua_pushstring ()
...
```

Or memory corruption:

```
*** Error in `XXXXXXXX': double free or corruption (out): 0x000000001a2c4070 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f3a0bf4a7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f3a0bf5337a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f3a0bf5753c]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(CRYPTO_free+0x1d)[0x7f3a0ca7c0cd]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(+0x10b598)[0x7f3a0cb24598]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(+0x10c1e0)[0x7f3a0cb251e0]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(ENGINE_finish+0x39)[0x7f3a0cb25319]
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0(EVP_CIPHER_CTX_cleanup+0x4c)[0x7f3a0cb38c1c]
...
```
Gdb data:

```
#0  0x00007ffff67dd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff67df02a in __GI_abort () at abort.c:89
#2  0x00007ffff681f7ea in __libc_message (do_abort=do_abort@entry=2,
    fmt=fmt@entry=0x7ffff6938ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff682837a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>,
    str=0x7ffff6938fe8 "double free or corruption (out)", action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ffff682c53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00007ffff73510cd in CRYPTO_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007ffff73f9598 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#8  0x00007ffff73fa1e0 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#9  0x00007ffff73fa319 in ENGINE_finish () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#10 0x00007ffff740dc1c in EVP_CIPHER_CTX_cleanup () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#11 0x00007ffff5720a6d in openssl_cipher_ctx_free (L=0x780e08) at lua-openssl-0.7.1/src/cipher.c:551
#12 0x00000000004d1044 in luaD_precall ()
#13 0x00000000004d1413 in luaD_call ()
#14 0x00000000004d1471 in luaD_callnoyield ()
#15 0x00000000004d089c in luaD_rawrunprotected ()
#16 0x00000000004d16dd in luaD_pcall ()
#17 0x00000000004d288f in GCTM ()
#18 0x00000000004d2932 in runafewfinalizers ()
#19 0x00000000004d3cd3 in singlestep ()
#20 0x00000000004d40c8 in luaC_fullgc ()
#21 0x00000000004cef6f in lua_gc ()
#22 0x00000000004e357f in luaB_collectgarbage ()
#23 0x00000000004d1044 in luaD_precall ()
#24 0x00000000004dbeed in luaV_execute ()
#25 0x00000000004d141f in luaD_call ()
#26 0x00000000004d1471 in luaD_callnoyield ()
#27 0x00000000004d089c in luaD_rawrunprotected ()
#28 0x00000000004d16dd in luaD_pcall ()
#29 0x00000000004ced57 in lua_pcallk ()
...
```

When the function is called, the OpenSSL context is destroyed. But the pointer value store in the lightuserdata remains.

When the garbage collector call the function __gc(), it try to clean and free again the OpenSSL CTX(), but the context is already freed.

Maybe, you van change the value of the light userdata after  the first cleanup/free, to put a NULL value.

Thierry

**Comment by zhaozg** [comment]
Thank you and your details info

**Comment by zhaozg** [comment]
Closed by https://github.com/zhaozg/lua-openssl/commit/6e5c8210b6a34e62d8cbd918610048c0389f4cad
