### ISSUE TITLE
x509_store_free bad access

### ISSUE THREAD

**Issue by rphillips** [zhaozg/lua-openssl#34]
lua-openssl is compiled against master (e54ba294).

Backtrace:
```
(gdb) bt
#0  0x00000001001ce78c in sk_value ()
#1  0x00000001001d8ada in X509_STORE_free ()
#2  0x00000001000f6d46 in SSL_CTX_free ()
#3  0x00000001000c67b9 in openssl_ssl_ctx_gc ()
#4  0x00000001000a9d5b in lj_BC_FUNCC ()
```

Steps to reproduce:

```
git clone --branch luvi-up --recursive https://github.com/virgo-agent-toolkit/virgo-base
make
make test or gdb ./base
```

**Comment by rphillips** [comment]
Checked out a new tree and it works. My bad.
